version: '3.5'
services:
    angular-img: # The name of the service
      container_name: angularcontainer  # Container name
      build:
        context: .
        dockerfile: ./Dockerfile
      volumes: # Volume binding
        - '.:/usr/src/app'
      ports:
        - '4200:4200' # Port mapping